from planner.models import *

def degreeComputerScience(newUserAccountPk):

	newUserAccount = UserAccount.objects.get(pk=newUserAccountPk)

	# create new degree plan
	newDegreePlan = DegreePlan(name='Computer Science', userAccount=newUserAccount)
	newDegreePlan.save()
	
	# create course groups for said degree plan
	newCourseGroup00 = CourseGroup(name='Computer Science', degreePlan=newDegreePlan, columnNumber=0)
	newCourseGroup01 = CourseGroup(name='Technical Electives', degreePlan=newDegreePlan, columnNumber=0)
	newCourseGroup02 = CourseGroup(name='Supporting Area', degreePlan=newDegreePlan, columnNumber=0)
	newCourseGroup03 = CourseGroup(name='Math and Statistics', degreePlan=newDegreePlan, columnNumber=1)
	newCourseGroup04 = CourseGroup(name='Science', degreePlan=newDegreePlan, columnNumber=1)
	newCourseGroup05 = CourseGroup(name='Citizenship', degreePlan=newDegreePlan, columnNumber=1)
	newCourseGroup06 = CourseGroup(name='General Elective', degreePlan=newDegreePlan, columnNumber=1)
	newCourseGroup07 = CourseGroup(name='English, Comm., and Writing', degreePlan=newDegreePlan, columnNumber=2)
	newCourseGroup08 = CourseGroup(name='Humanities', degreePlan=newDegreePlan, columnNumber=2)
	newCourseGroup09 = CourseGroup(name='Visual and Performing Arts', degreePlan=newDegreePlan, columnNumber=2)
	newCourseGroup10 = CourseGroup(name='Social Science Elective', degreePlan=newDegreePlan, columnNumber=2)
	newCourseGroup11 = CourseGroup(name='International and Cultural Diversity', degreePlan=newDegreePlan, columnNumber=2)
	newCourseGroup12 = CourseGroup(name='Physical Education', degreePlan=newDegreePlan, columnNumber=2)
	
	newCourseGroup00.save()
	newCourseGroup01.save()
	newCourseGroup02.save()
	newCourseGroup03.save()
	newCourseGroup04.save()
	newCourseGroup05.save()
	newCourseGroup06.save()
	newCourseGroup07.save()
	newCourseGroup08.save()
	newCourseGroup09.save()
	newCourseGroup10.save()
	newCourseGroup11.save()
	newCourseGroup12.save()
	
	# create course slots for said course groups
	newCourseSlot00 = CourseSlot(department='CSCE', number='121', hours='4', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup00)
	newCourseSlot01 = CourseSlot(department='CSCE', number='181', hours='1', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup00)
	newCourseSlot02 = CourseSlot(department='CSCE', number='221', hours='4', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup00)
	newCourseSlot03 = CourseSlot(department='CSCE', number='222', hours='3', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup00)
	newCourseSlot04 = CourseSlot(department='CSCE', number='312', hours='4', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup00)
	newCourseSlot05 = CourseSlot(department='CSCE', number='313', hours='4', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup00)
	newCourseSlot06 = CourseSlot(department='CSCE', number='314', hours='3', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup00)
	newCourseSlot07 = CourseSlot(department='CSCE', number='315', hours='3', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup00)
	newCourseSlot08 = CourseSlot(department='CSCE', number='481', hours='1', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup00)
	newCourseSlot09 = CourseSlot(department='CSCE', number='482', hours='3', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup00)
	newCourseSlot10 = CourseSlot(department='CSCE', number='411', hours='3', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup00)
	newCourseSlot11 = CourseSlot(department='CSCE', number='0', hours='3', isDepartmentEditable=False, isNumberEditable=True,isScheduled=False, notes='Upper division electives follow a track system; see the separate description on CPSC Upper Level Track of the degree plan.', courseGroup=newCourseGroup01)
	newCourseSlot12 = CourseSlot(department='CSCE', number='0', hours='3', isDepartmentEditable=False, isNumberEditable=True,isScheduled=False, notes='Upper division electives follow a track system; see the separate description on CPSC Upper Level Track of the degree plan.', courseGroup=newCourseGroup01)
	newCourseSlot13 = CourseSlot(department='CSCE', number='0', hours='3', isDepartmentEditable=False, isNumberEditable=True,isScheduled=False, notes='Upper division electives follow a track system; see the separate description on CPSC Upper Level Track of the degree plan.', courseGroup=newCourseGroup01)
	newCourseSlot14 = CourseSlot(department='CSCE', number='0', hours='3', isDepartmentEditable=False, isNumberEditable=True,isScheduled=False, notes='Upper division electives follow a track system; see the separate description on CPSC Upper Level Track of the degree plan.', courseGroup=newCourseGroup01)
	newCourseSlot15 = CourseSlot(department='CSCE', number='0', hours='3', isDepartmentEditable=False, isNumberEditable=True,isScheduled=False, notes='Upper division electives follow a track system; see the separate description on CPSC Upper Level Track of the degree plan.', courseGroup=newCourseGroup01)
	newCourseSlot16 = CourseSlot(department='CSCE', number='0', hours='3', isDepartmentEditable=False, isNumberEditable=True,isScheduled=False, notes='Upper division electives follow a track system; see the separate description on CPSC Upper Level Track of the degree plan.', courseGroup=newCourseGroup01)
	newCourseSlot17 = CourseSlot(department='XXXX', number='0', hours='3', isDepartmentEditable=True, isNumberEditable=True,isScheduled=False, notes='(A) Complete an official university recognized minor in an AREA APPROVED BY A CS ADVISOR. The student will be required to complete the courses mandated by the department offering the MINOR which will likely require 15+ credits to complete. NOT ALL OFFICIAL MINORS can be used to complete the supporting field requirement. At least 12 credits not otherwise used on the CPSC degree plan are required for completion of the supporting field. -OR- (B) Complete the 12 hour supporting area requirement on your degree plan. The CS ADVISOR MUST APPROVE THE SUBJECT AREA AND THE COURSES SELECTED. The minor must include 300 and 400 level courses and may be selected from the physical sciences, engineering, mathematics, business or liberal arts.', courseGroup=newCourseGroup02)
	newCourseSlot18 = CourseSlot(department='XXXX', number='0', hours='3', isDepartmentEditable=True, isNumberEditable=True,isScheduled=False, notes='(A) Complete an official university recognized minor in an AREA APPROVED BY A CS ADVISOR. The student will be required to complete the courses mandated by the department offering the MINOR which will likely require 15+ credits to complete. NOT ALL OFFICIAL MINORS can be used to complete the supporting field requirement. At least 12 credits not otherwise used on the CPSC degree plan are required for completion of the supporting field. -OR- (B) Complete the 12 hour supporting area requirement on your degree plan. The CS ADVISOR MUST APPROVE THE SUBJECT AREA AND THE COURSES SELECTED. The minor must include 300 and 400 level courses and may be selected from the physical sciences, engineering, mathematics, business or liberal arts.', courseGroup=newCourseGroup02)
	newCourseSlot19 = CourseSlot(department='XXXX', number='0', hours='3', isDepartmentEditable=True, isNumberEditable=True,isScheduled=False, notes='(A) Complete an official university recognized minor in an AREA APPROVED BY A CS ADVISOR. The student will be required to complete the courses mandated by the department offering the MINOR which will likely require 15+ credits to complete. NOT ALL OFFICIAL MINORS can be used to complete the supporting field requirement. At least 12 credits not otherwise used on the CPSC degree plan are required for completion of the supporting field. -OR- (B) Complete the 12 hour supporting area requirement on your degree plan. The CS ADVISOR MUST APPROVE THE SUBJECT AREA AND THE COURSES SELECTED. The minor must include 300 and 400 level courses and may be selected from the physical sciences, engineering, mathematics, business or liberal arts.', courseGroup=newCourseGroup02)
	newCourseSlot20 = CourseSlot(department='XXXX', number='0', hours='3', isDepartmentEditable=True, isNumberEditable=True,isScheduled=False, notes='(A) Complete an official university recognized minor in an AREA APPROVED BY A CS ADVISOR. The student will be required to complete the courses mandated by the department offering the MINOR which will likely require 15+ credits to complete. NOT ALL OFFICIAL MINORS can be used to complete the supporting field requirement. At least 12 credits not otherwise used on the CPSC degree plan are required for completion of the supporting field. -OR- (B) Complete the 12 hour supporting area requirement on your degree plan. The CS ADVISOR MUST APPROVE THE SUBJECT AREA AND THE COURSES SELECTED. The minor must include 300 and 400 level courses and may be selected from the physical sciences, engineering, mathematics, business or liberal arts.', courseGroup=newCourseGroup02)
	newCourseSlot21 = CourseSlot(department='MATH', number='151', hours='4', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup03)
	newCourseSlot22 = CourseSlot(department='MATH', number='152', hours='4', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup03)
	newCourseSlot23 = CourseSlot(department='MATH', number='302', hours='3', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup03)
	newCourseSlot24 = CourseSlot(department='MATH', number='0', hours='3', isDepartmentEditable=False, isNumberEditable=True,isScheduled=False, notes='MATH 304 or MATH 308', courseGroup=newCourseGroup03)
	newCourseSlot25 = CourseSlot(department='STAT', number='211', hours='3', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup03)
	newCourseSlot26 = CourseSlot(department='XXXX', number='0', hours='4', isDepartmentEditable=True, isNumberEditable=True,isScheduled=False, notes='16 hours of science coursework are required; choose from any two of the following four options. Only ONE option B may be used to satisfy this requirement. 1. Chemistry: CHEM 101/111 and 102/112 2. Physics: PHYS 218 and 208 3. Life Sciences: i. Option A: BIOL 111 and BIOL 112 ii. Option B: any two of: BIOL 111, BIOL 101, BIOL 107 4. Earth Sciences: i. Option A: GEOL 101 and GEOL 106 ii. Option B: any two of: GEOG 203, ATMO 201/202, RENR 205/215', courseGroup=newCourseGroup04)
	newCourseSlot27 = CourseSlot(department='XXXX', number='0', hours='4', isDepartmentEditable=True, isNumberEditable=True,isScheduled=False, notes='16 hours of science coursework are required; choose from any two of the following four options. Only ONE option B may be used to satisfy this requirement. 1. Chemistry: CHEM 101/111 and 102/112 2. Physics: PHYS 218 and 208 3. Life Sciences: i. Option A: BIOL 111 and BIOL 112 ii. Option B: any two of: BIOL 111, BIOL 101, BIOL 107 4. Earth Sciences: i. Option A: GEOL 101 and GEOL 106 ii. Option B: any two of: GEOG 203, ATMO 201/202, RENR 205/215', courseGroup=newCourseGroup04)
	newCourseSlot28 = CourseSlot(department='XXXX', number='0', hours='4', isDepartmentEditable=True, isNumberEditable=True,isScheduled=False, notes='16 hours of science coursework are required; choose from any two of the following four options. Only ONE option B may be used to satisfy this requirement. 1. Chemistry: CHEM 101/111 and 102/112 2. Physics: PHYS 218 and 208 3. Life Sciences: i. Option A: BIOL 111 and BIOL 112 ii. Option B: any two of: BIOL 111, BIOL 101, BIOL 107 4. Earth Sciences: i. Option A: GEOL 101 and GEOL 106 ii. Option B: any two of: GEOG 203, ATMO 201/202, RENR 205/215', courseGroup=newCourseGroup04)
	newCourseSlot29 = CourseSlot(department='XXXX', number='0', hours='4', isDepartmentEditable=True, isNumberEditable=True,isScheduled=False, notes='16 hours of science coursework are required; choose from any two of the following four options. Only ONE option B may be used to satisfy this requirement. 1. Chemistry: CHEM 101/111 and 102/112 2. Physics: PHYS 218 and 208 3. Life Sciences: i. Option A: BIOL 111 and BIOL 112 ii. Option B: any two of: BIOL 111, BIOL 101, BIOL 107 4. Earth Sciences: i. Option A: GEOL 101 and GEOL 106 ii. Option B: any two of: GEOG 203, ATMO 201/202, RENR 205/215', courseGroup=newCourseGroup04)
	newCourseSlot30 = CourseSlot(department='HIST', number='0', hours='3', isDepartmentEditable=False, isNumberEditable=True,isScheduled=False, notes='', courseGroup=newCourseGroup05)
	newCourseSlot31 = CourseSlot(department='HIST', number='0', hours='3', isDepartmentEditable=False, isNumberEditable=True,isScheduled=False, notes='', courseGroup=newCourseGroup05)
	newCourseSlot32 = CourseSlot(department='POLS', number='206', hours='3', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup05)
	newCourseSlot33 = CourseSlot(department='POLS', number='207', hours='3', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup05)
	newCourseSlot34 = CourseSlot(department='XXXX', number='0', hours='3', isDepartmentEditable=True, isNumberEditable=True,isScheduled=False, notes='An extra course that could fill another degree plan category. Three (3) hours of general electives are required and should be chosen from the approved list from the Academic Advisors.', courseGroup=newCourseGroup06)
	newCourseSlot35 = CourseSlot(department='ENGL', number='104', hours='3', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup07)
	newCourseSlot36 = CourseSlot(department='XXXX', number='0', hours='3', isDepartmentEditable=True, isNumberEditable=True,isScheduled=False, notes='One of ENGL 210, ENGL 301, COMM 203, COMM 205', courseGroup=newCourseGroup07)
	newCourseSlot37 = CourseSlot(department='XXXX', number='482', hours='3', isDepartmentEditable=True, isNumberEditable=False,isScheduled=False, notes='ENGR 482 (PHIL 482) is a required course. (You must take a writing intensive section of this class.)', courseGroup=newCourseGroup08)
	newCourseSlot38 = CourseSlot(department='XXXX', number='0', hours='3', isDepartmentEditable=True, isNumberEditable=True,isScheduled=False, notes='Three (3) hours of visual and performing arts electives must be selected from the list of College of Engineering directed electives for visual and performing arts - please refer to Page 18 of the undergraduate catalog.', courseGroup=newCourseGroup09)
	newCourseSlot39 = CourseSlot(department='XXXX', number='0', hours='3', isDepartmentEditable=True, isNumberEditable=True,isScheduled=False, notes='Three (3) hours of social science electives are required which must be selected from the list of College of Engineering directed electives for social science courses - please refer to Page 18 of the undergraduate catalog.', courseGroup=newCourseGroup10)
	newCourseSlot41 = CourseSlot(department='XXXX', number='0', hours='3', isDepartmentEditable=True, isNumberEditable=True,isScheduled=False, notes='Six hours (two courses) of cultural and international diversity are required. The list of courses that satisfy this requirement can be found on page 19 of the catalog. There are some courses on this list that also satisfy the social science (eg. Engl 251) or visual and perf. Arts (eg. Arts 150) requirements. If you select such courses you may satisfy two requirements with a single course. The total of 128 hours for this degree is based on the assumption that students will choose courses that satisfy two requirements to avoid the additional six hours of course work.', courseGroup=newCourseGroup11)
	newCourseSlot42 = CourseSlot(department='XXXX', number='0', hours='3', isDepartmentEditable=True, isNumberEditable=True,isScheduled=False, notes='Six hours (two courses) of cultural and international diversity are required. The list of courses that satisfy this requirement can be found on page 19 of the catalog. There are some courses on this list that also satisfy the social science (eg. Engl 251) or visual and perf. Arts (eg. Arts 150) requirements. If you select such courses you may satisfy two requirements with a single course. The total of 128 hours for this degree is based on the assumption that students will choose courses that satisfy two requirements to avoid the additional six hours of course work.', courseGroup=newCourseGroup11)
	newCourseSlot43 = CourseSlot(department='KINE', number='198', hours='1', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup12)
	newCourseSlot44 = CourseSlot(department='KINE', number='199', hours='1', isDepartmentEditable=False, isNumberEditable=False,isScheduled=False, notes='', courseGroup=newCourseGroup12)
	
	newCourseSlot00.save()
	newCourseSlot01.save()
	newCourseSlot02.save()
	newCourseSlot03.save()
	newCourseSlot04.save()
	newCourseSlot05.save()
	newCourseSlot06.save()
	newCourseSlot07.save()
	newCourseSlot08.save()
	newCourseSlot09.save()
	newCourseSlot10.save()
	newCourseSlot11.save()
	newCourseSlot12.save()
	newCourseSlot13.save()
	newCourseSlot14.save()
	newCourseSlot15.save()
	newCourseSlot16.save()
	newCourseSlot17.save()
	newCourseSlot18.save()
	newCourseSlot19.save()
	newCourseSlot20.save()
	newCourseSlot21.save()
	newCourseSlot22.save()
	newCourseSlot23.save()
	newCourseSlot24.save()
	newCourseSlot25.save()
	newCourseSlot26.save()
	newCourseSlot27.save()
	newCourseSlot28.save()
	newCourseSlot29.save()
	newCourseSlot30.save()
	newCourseSlot31.save()
	newCourseSlot32.save()
	newCourseSlot33.save()
	newCourseSlot34.save()
	newCourseSlot35.save()
	newCourseSlot36.save()
	newCourseSlot37.save()
	newCourseSlot38.save()
	newCourseSlot39.save()
	newCourseSlot41.save()
	newCourseSlot42.save()
	newCourseSlot43.save()
	newCourseSlot44.save()
	
	return newDegreePlan